use_frameworks!

platform :ios, '10.0'

target 'AZAlertController_Example' do
  pod 'AZAlertController', :path => '../'

  target 'AZAlertController_Tests' do
    inherit! :search_paths

    
  end
end
